Added suggestion for more understandable readme
net-partner-011-ab/code-crafter pull request #57
Opened 2024-02-20 19:01 UTC by Blazze23

I've added a few lines to the readme file so that it is more understandable to the new users, so that they can faster get the app up and running.

2024-02-20 21:27 UTC, Regis011 approved these changes
Nice!Thanks for the input 👍🏻

2024-02-21 05:43 UTC, belikenikola requested changes
@Blazze23 You have some extension for formating the code activated (such as ESlint or something else) and now it is hard to recognize your changes all together with automatic changes created by extension. 

Make sure to review your own PR first. :)

2024-02-26 19:12 UTC, Blazze23 commented
I'm using Prettier extension for formatting, so I'm not sure what caused the problem.
Anyway the lines I added for more understandable readme are the following: Line 36 - It is necessary to create access keys and tokens in AWS and Contentful, they can't be left blank as shown in the example below, otherwise the application won't work. Links for AWS and Contentful can be found below in the documentation section. (This was added at the end of the line 36)
Line 56 - #### 2. Local installation of dependencies

```shell
npm install
``` (this was added et the end of the line 56 and other step numbers where increased by 1)

2024-03-03 17:48 UTC, belikenikola approved these changes

2024-03-03 18:33 UTC, merged